version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y && apt-get install -y apt-transport-https ca-certificates curl
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update -y && apt-get install -y docker-ce docker-ce-cli containerd.io

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR in all regions..."
      - for REGION in $AWS_DEPLOY_REGIONS; do
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.$REGION.amazonaws.com;
        done

  build:
    commands:
      - echo "Building Docker image..."
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - docker build -t ${IMAGE_URI} .

      - echo "Tagging Docker image for multi-region deployment..."
      - for REGION in $AWS_DEPLOY_REGIONS; do
          docker tag ${IMAGE_URI} ${AWS_ACCOUNT_ID}.dkr.ecr.$REGION.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG};
        done

  post_build:
    commands:
      - echo "Pushing Docker image to all regions..."
      - for REGION in $AWS_DEPLOY_REGIONS; do
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.$REGION.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG};
        done

      - echo "Starting sequential deployment to Kubernetes clusters..."
      - for REGION in $AWS_DEPLOY_REGIONS; do
          echo "Updating EKS cluster in $REGION..."
          aws eks update-kubeconfig --region $REGION --name my-cluster-$REGION --alias my-cluster-$REGION || exit 1
          
          echo "Verifying Kubernetes context..."
          kubectl config use-context my-cluster-$REGION || exit 1
          kubectl config current-context || exit 1
          kubectl cluster-info || exit 1

          echo "Deploying new image to Kubernetes in $REGION..."
          kubectl set image deployment/my-deployment my-container=${AWS_ACCOUNT_ID}.dkr.ecr.$REGION.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG} --record || exit 1
          
          echo "Verifying deployment status in $REGION..."
          kubectl rollout status deployment/my-deployment --timeout=90s || exit 1
          
          echo "Deployment successful in $REGION, proceeding to the next region..."
        done

artifacts:
  files:
    - imagedefinitions.json
