apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: 2  # Adjust as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_DEFAULT_REGION>.amazonaws.com/<IMAGE_REPO_NAME>:latest
          imagePullPolicy: Always  # Ensures the latest image is always pulled
          ports:
            - containerPort: 80  # Adjust based on your app
      imagePullSecrets:
        - name: ecr-secret  # Needed if using private ECR repo

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Adjust based on your app
  type: LoadBalancer  # Change to ClusterIP or NodePort if needed
